imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

tree_house_worker:
    queue:
        server: localhost
tree_house_worker:
     pheanstalk: leezy.pheanstalk

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: null
    fragments:       ~
    http_method_override: true


